- carsdata/src/components/UDScomponents/DivCenterBattery.tsx
- carsdata/src/components/UDScomponents/ModalUDS.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
- carsdata/src/utils/ApiManager.ts
Integrated the API Manager into the Battery component. Also did some reworks that helped improving the code. Added relevant comments where they were needed and solved the design problem, aligning the buttons.
> Integrated API Manager with Battery + other reworks

- carsdata/src/components/mainPageComponents/MainPage.tsx
- carsdata/src/utils/VINValidation.ts
New feature:
- add validation for VIN
> add VIN validation

- carsdata/src/components/UDScomponents/DivCenterBattery.tsx
- carsdata/src/components/UDScomponents/DivCenterEngine.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
Reworked Engine ECU component.
> Reworked Engine ECU

- carsdata/src/components/UDScomponents/DivCenterDoors.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
New feature: Integrate API Call Manager for Doors ECU
Trello link: https://trello.com/c/i33uBIrj/103-api-manager-integrate-for-doors-rework
> Integrate API Manager for doors

- carsdata/src/app/UDS/hvac/page.tsx
- carsdata/src/components/UDScomponents/DivCenterHVAC.tsx
- carsdata/src/components/UDScomponents/ModalHvacModes.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
- carsdata/src/utils/ApiManager.ts
Reworked HVAC module page and fixed read and write. Also fixed design issues and created a new modal for HVAC Modes.
> Rework HVAC + integrate with API manager

- carsdata/src/components/UDScomponents/SendRequests.tsx
-integrated Api Manager for the "send frame" service;
-the can frames works well.
Trello link: https://trello.com/c/C754aIlq/107-refactoring-send-frame-service-on-the-standalone-app
Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Integrated Api Manager for send frame service & tested frames

- carsdata/src/utils/Logger.ts
Replaced localStorage with sessionStorage to ensure it will be cleared between sessions. Also added a logic for when the storage is full (the logs will be trimmed).
> Solved Logger bug

- carsdata/src/utils/ApiManager.ts
Implemented Read DTC logic in API Manager. It needed a special case because its URL takes a lot of unique flags.
> Implemented Read DTC logic in API Manager

- carsdata/src/components/UDScomponents/ModalClearDTC.tsx
Implemented modal for Clear DTC
> Implemented modal for Clear DTC

- carsdata/package-lock.json
- carsdata/package.json
- carsdata/src/app/UDS/battery/page.tsx
- carsdata/src/app/UDS/doors/page.tsx
- carsdata/src/app/UDS/engine/page.tsx
- carsdata/src/app/UDS/hvac/page.tsx
- carsdata/src/app/UDS/mcu/page.tsx
- carsdata/src/app/UDS/page.tsx
- carsdata/src/app/UDS/send-requests/page.tsx
- carsdata/src/components/UDScomponents/DivLeft.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
- carsdata/src/components/mainPageComponents/NavBarMain.tsx
Fixed read and write in send request section
> Read write in send request fixed

- carsdata/src/components/UDScomponents/ModalReadDTC.tsx
> Created modal for Read DTC

- carsdata/src/utils/Logger.ts
Fixed the logger related errors that appeared during server-side components.
> Fixed small logger bug

- carsdata/src/components/UDScomponents/SendRequests.tsx
- I have created the Clear DTC function, implemented the Api Manager function for it;
- also integrated the module for this service into the button, which includes the two available ECUs, battery and engine, covering the set of 5 parameters to be cleared.
Trello link: https://trello.com/c/o0aQR5oG/113-clear-dtc-integrate-api-manager
New feature (non-breaking change which adds functionality)
> Clear DTC service implemented in the standalone app

- carsdata/src/components/UDScomponents/SendRequests.tsx
Add other ECUs to ECU Reset dropdown.
> Enabled all ECUs for ECU Reset dropdown

- carsdata/src/components/UDScomponents/SendRequests.tsx
Integrated the read dtc service with api manager and also integrated the new modal. 
+ refactorization for response
> Integrate Read DTC with Api Manager

- carsdata/src/components/UDScomponents/DivCenterBattery.tsx
- carsdata/src/components/UDScomponents/SendRequests.tsx
- carsdata/src/utils/ApiManager.ts
Small fix for battery:
- changed Battery level to Energy level in battery page;
- changed % to Wh as unit of measurement for the new Energy level;
- replaced state_of_charge parameter with battery_state_of_charge;
> Small fix for battery

- carsdata/src/components/UDScomponents/SendRequests.tsx
Fixed the Write Access Timing service
> Write access Timing fix

- carsdata/src/components/UDScomponents/EcuActions.ts
Created the ECU Actions class and moved methods for ecu reset, read/write access timing and read/clear dtc in it.
> Create ECU Actions class

- carsdata/src/components/OTAcomponents/OTApage.tsx
- carsdata/src/components/OTAcomponents/TableVersionControl.tsx
- carsdata/src/components/OTAcomponents/UpgradeButton.tsx
- carsdata/src/components/UDScomponents/DivCenterBattery.tsx
- carsdata/src/components/UDScomponents/DivCenterDoors.tsx
- carsdata/src/components/UDScomponents/DivCenterEngine.tsx
- carsdata/src/components/UDScomponents/DivCenterHVAC.tsx
- carsdata/src/components/UDScomponents/DivCenterMCU.tsx
- carsdata/src/components/UDScomponents/EcuActions.ts
- carsdata/src/components/UDScomponents/SendRequests.tsx
- carsdata/src/components/sharedComponents/LoadingCircle.ts
- carsdata/src/utils/ApiManager.ts
Moved the asynchronous operations in API Manager and updated the calls in the ECU Pages.
> Improved API Manager and updated ECU pages

- carsdata/src/components/UDScomponents/SendRequests.tsx
- correcting the logic and using an appropriate check for the API response;
-  the session was updated correctly;
-  the toggle started reflecting this change properly in the UI.
> Fixed toggle for the change session service
